export enum cart{
    cartWrapper = 'cart-wrapper',
    cartSingleItem = 'cart-single-item-',
    cartImage = 'cart-item-image-',
    cartTitle = 'cart-item-title-',
    cartPrice = 'cart-item-price-',
    cartCount = 'cart-item-count-',
    cartPriceWithAccesories = 'cart-single-item-total-price-',
    cartDeleteItem = 'cart-delete-item-',
    cartWarrantyTitle = 'cart-warranty-title-',
    cartWarrantyPrice = 'cart-warranty-price-',
    cartWarrantyDelete = 'cart-warranty-delete-',
    cartReturnOptionTitle = 'cart-return-option-title',
    cartReturnOptionPrice = 'cart-return-option-price',
    cartReturnOptionDelete = 'cart-return-option-delete',

    cartPriceWithoutDPHTitle = 'cart-price-without-DPH-title',
    cartPriceWithoutDPHPrice = 'cart-price-without-DPH-price',
    cartDPHTitle = 'cart-DPH-title',
    cartDPHPrice = 'cart-DPH-price',
    cartTotalPriceTitle = 'cart-total-price-title',
    cartTotalPricePrice = 'cart-total-price-price',

    cartBackToShopNavigation = 'cart-back-to-shop-navigation',
    cartBillingNavigation = 'cart-billing-navigation',
}