export enum filters{
    filter= 'filter',
    filterTitle = 'filter-title',
    filterSearchSection= ' filter-search-section',
    filterSearchTitle= ' filter-search-title',
    filterSearchInput = 'filter-search-input',
    filterCategorySection= ' filter-category-section',
    filterCategoryTitle= ' filter-category-title',
    filterCategoryButton = 'filter-category-button-',
    filterPriceSection = 'filter-price-section',
    filterPriceTitle = 'filter-price-title',
    filterPriceInput = 'filter-price-input',
    filterOrderSection = 'filter-order-section',
    filterOrderTitle = 'filter-order-title',
    filterOrderCheapest = 'filter-order-cheapest',
    filterOrderExpensive = 'filter-order-expensive',
    filterOrderAlphabet = 'filter-order-alphabet',
    filterOrderReverseAplhabet = 'filter-order-reverse-alphabet',

}